### ISSUE TITLE
Cookie 상품에 걸어보기

### ISSUE THREAD

**Issue by Cutiepazzipozzi** [Cutiepazzipozzi/API-Practice#6]
- [ ] 일단 상품에 cookie 설정 해보기
- [x]  성공하면 다른 항목에도 설정하기
- [x] 멤버 항목 만들어 쿠키 및 세션으로 설정 (연습)

**Comment by sk000801** [comment]
일단 쇼핑몰 클론코딩 member 로그인 부분에 걸어둠! 너무 많은 정보를 저장하면 보안에서 위험성이 생기기 때문에 
회원 로그인에만 사용해볼 생각...
